#git作为基础镜像
FROM bitnami/git

#切换目录，指定源码克隆后保存位置
WORKDIR /usr/local/code

#拉取源代码
#如果私有仓卡记得加账号密码
RUN git clone https://github.com/Leeson0202/Test.git

FROM maven:3.8.4-ibmjava-8-alpine

#切换目录，指定编译源码位置
WORKDIR /usr/local/code

#将源码复制到下一个镜像中
COPY --from=0 /usr/local/code/Test /usr/local/code

#maven编译打包java代码
RUN mvn install

FROM openjdk:8u212-jre-alpine

#切换目录，指定jar存放位置
WORKDIR /usr/local/code

COPY --from=1 /usr/local/code/target/Test-0.0.1-SNAPSHOT.jar /usr/local/code

#声明项目所用端口
EXPOSE 8080

#启动java项目程序
ENTRYPOINT ["java","-jar","Test-0.0.1-SNAPSHOT.jar"]

